/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.integrado.gIRC2;

import model.LoginModelo;
import model.MensagemModelo;
import br.integrado.gIRC2.LoginFrame;
import controller.MensagemController;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JEditorPane;


/**
 *
 * @author Gian Carlo Mantuan
 */
public class MensagensFrame extends javax.swing.JFrame {

    private MensagemModelo modmensagem = new MensagemModelo();
    private MensagemController daomensagem = new MensagemController();
    public Integer id;
    public ResultSet messages;
    public String todas;
    public Boolean isCreate = true;
    public Integer idf = -1;
    public String messagef;
    
    /**
     * Creates new form MensagensFrame
     */
    public MensagensFrame(Integer usuarioId, String username) {
        initComponents();
        this.id = usuarioId;
        setUserName(username);
        fetchMessages();
    }

        
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMessageInputField = new javax.swing.JTextField();
        jSendButton = new javax.swing.JButton();
        jMenssagePane = new javax.swing.JScrollPane();
        jTextArea = new javax.swing.JTextArea();
        jUsuarioLabel = new javax.swing.JLabel();
        jDeleteMessageButton = new javax.swing.JButton();
        jEditMessageButton = new javax.swing.JButton();
        jTitleLabel = new javax.swing.JLabel();
        jUsernameLabel = new javax.swing.JLabel();
        jExitButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("gIRC");
        setResizable(false);

        jSendButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/send.png"))); // NOI18N
        jSendButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSendButtonActionPerformed(evt);
            }
        });

        jTextArea.setEditable(false);
        jTextArea.setColumns(20);
        jTextArea.setRows(5);
        jMenssagePane.setViewportView(jTextArea);

        jDeleteMessageButton.setText("Apagar minha ultima mensagem");
        jDeleteMessageButton.setMaximumSize(new java.awt.Dimension(220, 30));
        jDeleteMessageButton.setMinimumSize(new java.awt.Dimension(220, 30));
        jDeleteMessageButton.setPreferredSize(new java.awt.Dimension(220, 30));
        jDeleteMessageButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jDeleteMessageButtonActionPerformed(evt);
            }
        });

        jEditMessageButton.setText("Editar minha ultima mensagem");
        jEditMessageButton.setMaximumSize(new java.awt.Dimension(220, 30));
        jEditMessageButton.setMinimumSize(new java.awt.Dimension(220, 30));
        jEditMessageButton.setPreferredSize(new java.awt.Dimension(220, 30));
        jEditMessageButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jEditMessageButtonActionPerformed(evt);
            }
        });

        jTitleLabel.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        jTitleLabel.setText("Usuário:");

        jUsernameLabel.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jUsernameLabel.setText("undefined");

        jExitButton.setBackground(new java.awt.Color(255, 0, 51));
        jExitButton.setForeground(new java.awt.Color(255, 255, 255));
        jExitButton.setText("Sair");
        jExitButton.setMaximumSize(new java.awt.Dimension(50, 30));
        jExitButton.setMinimumSize(new java.awt.Dimension(50, 30));
        jExitButton.setPreferredSize(new java.awt.Dimension(50, 30));
        jExitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jExitButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jMenssagePane, javax.swing.GroupLayout.DEFAULT_SIZE, 469, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jMessageInputField)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSendButton, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jDeleteMessageButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jEditMessageButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jUsuarioLabel)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTitleLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jUsernameLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jExitButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jUsuarioLabel)
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTitleLabel)
                    .addComponent(jUsernameLabel)
                    .addComponent(jExitButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jMenssagePane, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jDeleteMessageButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jEditMessageButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSendButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jMessageInputField, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
        
    private void jSendButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSendButtonActionPerformed
        modmensagem.setMensagem(jMessageInputField.getText());
        modmensagem.setUsuario(this.id);
        
        if (isCreate) {            
            if (!modmensagem.getMensagem().isEmpty()){
                daomensagem.sendMessage(modmensagem);                
            }    
        } else {
            if (!modmensagem.getMensagem().isEmpty()){
                daomensagem.updateMessage(idf, jMessageInputField.getText());                                
            } 
            idf = -1;
            jEditMessageButton.setText("Editar minha última mensagem");
            isCreate = true;
        }
        
        jMessageInputField.setText("");            
        jTextArea.setText("");
        todas = "BEM VINDO AO CHAT \n";
        fetchMessages();                 
    }//GEN-LAST:event_jSendButtonActionPerformed

    private void jDeleteMessageButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jDeleteMessageButtonActionPerformed
        try {                                                     
            Integer idf = -1;
            messages = daomensagem.getMessage();
            messages.next();
           
            
            if (messages.first() == true) {
                while(!messages.isAfterLast()) {
                    try {
                        if(messages.getInt("usuarioId") == this.id) {
                            idf = messages.getInt("mensagemId");
                        }
                        messages.next();
                    } catch (SQLException ex) {
                        JOptionPane.showMessageDialog(null, "Erro ao deletar mensagens");
                    }
                }
                
                System.out.println(idf);
                if (idf > 0) {
                    daomensagem.deleteMessage(idf);
                    fetchMessages();
                    idf = -1;
                }
            }
            
        } catch (SQLException ex) {
            Logger.getLogger(MensagensFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_jDeleteMessageButtonActionPerformed

    private void jEditMessageButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jEditMessageButtonActionPerformed
         
        try {
            messages = daomensagem.getMessage();
            messages.next();
            
            if (messages.first() == true) {
                while(!messages.isAfterLast()) {
                    try {
                        if(messages.getInt("usuarioId") == this.id) {
                            idf = messages.getInt("mensagemId");
                            messagef = messages.getString("mensagem");
                        }
                        messages.next();
                    } catch (SQLException ex) {
                        JOptionPane.showMessageDialog(null, "Erro ao editar sua mensagem");
                    }
                }
                sendOrEdit(messagef);
            }
        } catch (SQLException ex) {
            Logger.getLogger(MensagensFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jEditMessageButtonActionPerformed

    private void jExitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jExitButtonActionPerformed
        setVisible(false);
            new LoginFrame().setVisible(true);
    }//GEN-LAST:event_jExitButtonActionPerformed
    
    public void sendOrEdit(String inputText) {        
        isCreate = !isCreate;
        if (isCreate == false) {
            jMessageInputField.setText(inputText);
            jEditMessageButton.setText("Cancelar a edição");
        } else {
            jMessageInputField.setText("");
            jEditMessageButton.setText("Editar minha última mensagem");
        }
    }
    
    public void setUserName (String username){
        jUsernameLabel.setText(username);
    }   
    
    public void fetchMessages() {
        try {
            messages = daomensagem.getMessage();
            messages.next();
            
            if (messages.first() == false) {
                todas = "BEM VINDO AO CHAT \n";
            } else {
                try {
                    todas = "BEM VINDO AO CHAT \n";
                    while(!messages.isAfterLast()) {
                        try {
                            todas = todas + messages.getString("nome") + ": \t " + messages.getString("mensagem") + "\n";
                            messages.next();
                        } catch (SQLException ex) {
                            JOptionPane.showMessageDialog(null, "Ops! Ocorreu um erro ao buscar as mensagens do servidor");
                        }
                    }
                } catch (SQLException ex) {
                    Logger.getLogger(MensagensFrame.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
            jTextArea.setText(todas);
        } catch (SQLException ex) {
            Logger.getLogger(MensagensFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MensagensFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MensagensFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MensagensFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MensagensFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MensagensFrame(0, "undefined").setVisible(true);
            }
        });
    }

   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jDeleteMessageButton;
    private javax.swing.JButton jEditMessageButton;
    private javax.swing.JButton jExitButton;
    private javax.swing.JScrollPane jMenssagePane;
    private javax.swing.JTextField jMessageInputField;
    private javax.swing.JButton jSendButton;
    private javax.swing.JTextArea jTextArea;
    private javax.swing.JLabel jTitleLabel;
    private javax.swing.JLabel jUsernameLabel;
    private javax.swing.JLabel jUsuarioLabel;
    // End of variables declaration//GEN-END:variables
}

